config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :tweeets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'tweeets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweeets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController








    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
        
    end

end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweeets or /tweeets.json
  def index
    @tweeet = Tweeet.new
    @tweeets = Tweeet.all.order('created_at DESC')
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
    
  end

  # GET /tweeets/new
  def new
    @tweeet = current_user.tweeets.build
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = current_user.tweeets.build(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to root_path, notice: "Tweeet was successfully created." }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy

    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice%></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="notice"><%= alert%></p>
      </div>
    <% end %>

    <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
    <article class="media box">
        <figure class="media-left">
            <p class="image is 64x64">
               <img src="https://media.vandal.net/i/ivandal/1200x630/75621/megaman-x-dive-202181915382475_1.jpg" style="width:64px;"alt="img"> 
            </p>
        </figure>
        <div class="media-content">
            <%= render "tweeets/form"%>
        </div>
    </article>


    <% @tweeets.each do |tweeet| %>
        <div class="box">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="https://64.media.tumblr.com/7c9a83289473d34653b936d0f91dc866/f138d3dace6c7f7c-94/s400x600/6750312615842e50f8af14f0e1d61b198d46d477.pnj">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <strong><%=tweeet.user.name%> </strong></br>
                        <small><%="@#{tweeet.user.username}"%></small></br>
                        <p><%= tweeet.tweeet %></p>
                    </div>
                    <div class="level">
                        <div class="level-left is-mobile">
                            <%= button_to tweeet, class:"button level-item", style:"border:none" do%>
                                <span class="icon"><i class="fa fa-link" aria-hidden = "true"></i></span>                        
                            <%end%>
                            <%= button_to edit_tweeet_path(tweeet), class:"button level-item", style:"border:none" do%>
                                <span class="icon"><i class="fa fa-pencil" aria-hidden = "true"></i></span>                        
                            <%end%>
                            <%= button_to tweeet, method: :delete, data: { confirm: "Tas seguro mi bra?"} ,class:"button level-item", style:"border:none" do%>
                                <span class="icon"><i class="fa fa-trash" aria-hidden = "true"></i></span>                        
                            <%end%>
                        </div>
                    </div>
                </div>
            </article>
        </div>

    <% end %>
</div>

app/views/tweeets/_form.html.erb
<%= simple_form_for(@tweeet) do |f|%>

  <% f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :tweeet, label: "Tweeetea sobre esto", input_html: { class: "textarea" }, wrapper: false, label_html: { class:'label'}, placeholder: 'Empieza tu tweeet...' %>
    </div>
  </div>
  <%= f.button :submit , "Enviar tweeet",class: 'button is-info' %>


<%  end %>

app/views/tweeets/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">
            Trendings mundiales
        </p>

        <a class="panel-block">
            ¿Sumeru 3.0?
        </a>

        <a class="panel-block">
            Amber merece cadena perpetua
        </a>

        <a class="panel-block">
            Se retrasa genshin 2.7 debido a c-19 en Shangai, China
        </a>
        
        <a class="panel-block">
            Los huevos no son tuyos, son de ella
        </a>

        <a class="panel-block">
            Ooohhh me vengo
        </a>

        <a class="panel-block">
            Tercera temporada de Mushoku Tensei: fecha y hora
        </a>

    </nav>  

</div>

app/views/tweeets/_tweeet.html.erb
<tr>
<td> <%= tweeet.tweeet %></td>
<td> <%= link_to "Mostrar tweet", tweeet %></td>
<td> <%= link_to "Editar", edit_tweeet_path(tweeet) %></td>
<td> <%= link_to "Eliminar", tweeet, method: :destroy, data: { confirm: "Estas seguro mi bra?"} %></td>
</tr>

app/views/tweeets/_who-to-follow.html.erb
<div class="column is-one-quarter ">
    <nav class="panel is-info">
        <p class="panel-heading">
            Who To Follow
        </p>
    <nav class="panel-block">
        <div class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.redd.it%2Faxsjk4gybaz31.png&f=1&nofb=1" style="height:64px;" alt="profile">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Anya Forger</strong>
                        <small>@smug_face</small>

                    </p>
                </div>
                <button class="is-inverted btn-hover-info button"  style=" width: 150px ;border-color:rgb(62,142,208); border-radius:45px">
                    <strong>    Follow    </strong>
                </button>
            </div>
        </div>
    </nav>

    <nav class="panel-block">
        <div class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://www.smitefire.com/images/god/icon/ra.png" style="height:64px;" alt="profile">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Smite Ra</strong>
                        <small>@fandefaragod</small>

                    </p>
                </div>
                <button class="is-inverted btn-hover-info button"  style=" width: 150px ;border-color:rgb(62,142,208); border-radius:45px">
                    <strong>    Follow    </strong>
                </button>
            </div>
        </div>
    </nav>

    <nav class="panel-block">
        <div class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.parisfans.fr%2Fwp-content%2Fuploads%2F2018%2F03%2FCristiano-Ronaldo.jpg&f=1&nofb=1" style="height:64px;" alt="profile">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Cristiano Ronaldo</strong>
                        <small>@elbicho</small>

                    </p>
                </div>
                <button class="is-inverted btn-hover-info button"  style="width: 150px ;border-color:rgb(62,142,208); border-radius:45px">
                    <strong>    Follow    </strong>
                </button>
            </div>
        </div>
    </nav>

    <nav class="panel-block">
        <div class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fc7%2F6f%2F33%2Fc76f337f4e673e0c0cc27869745918a3.jpg&f=1&nofb=1" style="height:64px;" alt="profile">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Fischl</strong>
                        <small>@imnotamy</small>

                    </p>
                </div>
                <button class="is-inverted btn-hover-info button"  style=" width: 150px ;border-color:rgb(62,142,208); border-radius:45px">
                    <strong>    Follow    </strong>
                </button>
            </div>
        </div>
    </nav>  

    <nav class="panel-block">
        <div class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload-os-bbs.hoyolab.com%2Fupload%2F2021%2F02%2F14%2F83259553%2F35998c7b9e6008092948ce0fe97fd6e7_708192978579664538.png%3Fx-oss-process%3Dimage%2Fresize%2Cs_740%2Fquality%2Cq_80%2Fauto-orient%2C0%2Finterlace%2C1%2Fformat%2Cpng&f=1&nofb=1" style="height:32px;" alt="profile">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Encuentra gente que conozcas</strong>
                    </p>
                    <p>
                        <small>Busca perfiles de tus amigos.</small>
                    </p>
                    
                </div>
            </div>
        </div>
    </nav>  



</div>

app/views/tweeets/edit.html.erb
<h1>Editing tweeet</h1>

<%= render "form", tweeet: @tweeet %>

<br>

<div>
  <%= link_to "Show this tweeet", @tweeet %> |
  <%= link_to "Back to tweeets", tweeets_path %>
</div>

app/views/tweeets/index.html.erb
<section class="section">
  <div class="container">
     <div class="columns">
         <%= render 'trends' %>
        <%= render 'feed' %>
        <%= render 'who-to-follow' %>
     </div>
  </div>

</section>

app/views/tweeets/new.html.erb
<h1>New tweeet</h1>

<%= render "form", tweeet: @tweeet %>

<br>

<div>
  <%= link_to "Back to tweeets", tweeets_path %>
</div>

app/views/tweeets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweeet %>

<div>
  <%= link_to "Edit this tweeet", edit_tweeet_path(@tweeet) %> |
  <%= link_to "Back to tweeets", tweeets_path %>

  <%= button_to "Destroy this tweeet", @tweeet, method: :delete %>
</div>